<a href="https://colab.research.google.com/github/shree0140/Python_Libraries_Basics/blob/main/Numpy_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY:

Array Creation:

In [19]:
import numpy as np
arr_1 = np.array([1,2,3,4,5])
print(arr_1)

[1 2 3 4 5]


In [20]:
arr_2 = np.arange(0,10,2)
print(arr_2)

[0 2 4 6 8]


In [21]:
arr_3 = np.linspace(0,10,5)
print(arr_3)

[ 0.   2.5  5.   7.5 10. ]


In [22]:
arr_4 = np.zeros((2,2))
print(arr_4)

[[0. 0.]
 [0. 0.]]


In [23]:
arr_5 = np.ones((4,5))
print(arr_5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
#arr_6 = np.eye(6)
arr_6 = np.identity(6)
print(arr_6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [26]:
string_1 = "Python"
arr_7 = np.fromiter(string_1, dtype="U2")
print(arr_7)

['P' 'y' 't' 'h' 'o' 'n']


Random Number Generation:

In [27]:
import random
arr_1 = np.random.rand(5)
print(arr_1)

[0.35011779 0.00653216 0.49730409 0.02744359 0.45290854]


In [30]:
arr_val = np.random.randint(1,100)
print(arr_val)
arr_2 = np.random.randint(1,100,10)
print(arr_2)

75
[88 51 79 49 81 15 64 25 95 90]


In [34]:
choice_list = [1,2,3,4,5]
choice = np.random.choice(choice_list)
print(choice)

3


In [36]:
shuffle_list = [1,2,3,4,5]
np.random.shuffle(shuffle_list)
print(shuffle_list)

[5, 4, 1, 3, 2]


In [42]:
np.random.seed(10)
random_no = np.random.randint(0,100,5)
print(random_no)

[ 9 15 64 28 89]


Array Manipulation:

In [43]:
arr_1 = [1,2,3,4,5,6]
reshaped_arr = np.reshape(arr_1,(2,3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [49]:
arr_2 = np.array([[1, 2, 3],[4, 5, 6]])
#print(arr_2)
flat_array = np.ravel(arr_2)
print(flat_array)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [51]:
arr_2 = np.array([[1, 2, 3],[4, 5, 6]])
transposed_array = np.transpose(arr_2)
print(transposed_array)

[[1 4]
 [2 5]
 [3 6]]


In [59]:
arr_2 = np.array([[1, 2, 3],[4, 5, 6]])
arr_3 = np.array([[1, 2, 3],[4, 5, 6]])
concatenated_array_col_wise = np.concatenate((arr_2,arr_3))
print(concatenated_array_col_wise)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [60]:
arr_1 = [1,2,3]
arr_2 = [4,5,6]
concatenated_array = np.concatenate((arr_1,arr_2))
print(concatenated_array)

[1 2 3 4 5 6]


In [61]:
arr_2 = np.array([[1, 2, 3],[4, 5, 6]])
arr_3 = np.array([[1, 2, 3],[4, 5, 6]])
vertically_stacked =np.vstack((arr_2,arr_3))
print(vertically_stacked)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [62]:
arr_2 = np.array([[1, 2, 3],[4, 5, 6]])
arr_3 = np.array([[1, 2, 3],[4, 5, 6]])
horizontally_stacked =np.hstack((arr_2,arr_3))
print(horizontally_stacked)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [64]:
arr = np.array([1,2,3,4,5,6,7,8])
splits = np.split(arr,2)
print(splits)
print(type(splits))

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
<class 'list'>


In [65]:
arr = np.array([1,2,3,4,5,6,7,8])
appended_arr= np.append(arr,9)
print(appended_arr)

[1 2 3 4 5 6 7 8 9]


In [66]:
arr = np.array([1,2,3,4,5,6,7,8])
del_val = np.delete(arr, 2)
print(del_val)

[1 2 4 5 6 7 8]


In [67]:
arr = np.array([1,2,3,4,5,6,7,8])
np.random.shuffle(arr)
print(arr)
sorted_arr = np.sort(arr)
print(sorted_arr)

[4 5 7 3 2 8 1 6]
[1 2 3 4 5 6 7 8]


Mathematical Operatios:

In [68]:
arr = np.array([1,2,3])
sum = np.sum(arr)
print(sum)

6


In [69]:
arr = np.array([1,2,3])
print(np.mean(arr))

2.0


In [70]:
arr = np.array([1,2,3])
print(np.min(arr))

1


In [71]:
arr = np.array([1,2,3])
print(np.max(arr))

3


In [72]:
arr = np.array([1,2,3])
print(np.std(arr))

0.816496580927726


In [73]:
arr = np.array([1,2,3])
print(np.prod(arr))

6


In [76]:
arr = np.array([1,2,3])
arr_2 = np.array([1,2,3])
print(np.power(arr,arr_2))

[ 1  4 27]


Array Descriptive Attribute:

In [83]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)

(8,)
8
1
int64
8


Other Methods:

In [78]:
arr = np.array([1,2,3,4,5,6,7,8])
copied_arr = np.copy(arr)
print(copied_arr)

[1 2 3 4 5 6 7 8]


In [79]:
arr = np.array([1,2,3,4,5,6,7,8])
filtered_output = np.where(arr <5, "lower", "upper")
print(filtered_output)

['lower' 'lower' 'lower' 'lower' 'upper' 'upper' 'upper' 'upper']


In [80]:
arr = np.array([1,2,3,4,5,6,7,8])
position = np.searchsorted(arr,5)
print(position)

4


In [81]:
arr = np.array([1,1,1,2,3,4,4,4,5,6,6,7,8])
unique_array = np.unique(arr)
print(unique_array)

[1 2 3 4 5 6 7 8]


In [85]:
arr = np.array([1,2,3,4,5,6,7,8])
arr.astype(str)
print(arr.dtype)

int64


In [86]:
arr = np.array([1,2,3,4,5,6,7,8])
for i in np.nditer(arr):
  print(i)

1
2
3
4
5
6
7
8


In [89]:
arr = np.array([1,2,3,4,5,6,7,8])
for idx,i in np.ndenumerate(arr):
  print(idx,i)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8


In [94]:
arr =np.array([1,2,3,4,5,6,7,8,9])
percentile_val = np.percentile(arr,[25,50])
print(percentile_val)
print(percentile_val.dtype)

[3. 5.]
float64
