NUMPY:

Array Creation:

In [19]:
import numpy as np
arr_1 = np.array([1,2,3,4,5])
print(arr_1)

[1 2 3 4 5]


In [20]:
arr_2 = np.arange(0,10,2)
print(arr_2)

[0 2 4 6 8]


In [21]:
arr_3 = np.linspace(0,10,5)
print(arr_3)

[ 0.   2.5  5.   7.5 10. ]


In [22]:
arr_4 = np.zeros((2,2))
print(arr_4)

[[0. 0.]
 [0. 0.]]


In [23]:
arr_5 = np.ones((4,5))
print(arr_5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
#arr_6 = np.eye(6)
arr_6 = np.identity(6)
print(arr_6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [26]:
string_1 = "Python"
arr_7 = np.fromiter(string_1, dtype="U2")
print(arr_7)

['P' 'y' 't' 'h' 'o' 'n']
